#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
# Source0 file verified with key 0x275C532289DD0F4A (raulcd@apache.org)
#
Name     : apache-arrow
Version  : 17.0.0
Release  : 1
URL      : https://dlcdn.apache.org/arrow/arrow-17.0.0/apache-arrow-17.0.0.tar.gz
Source0  : https://dlcdn.apache.org/arrow/arrow-17.0.0/apache-arrow-17.0.0.tar.gz
Source1  : https://dlcdn.apache.org/arrow/arrow-17.0.0/apache-arrow-17.0.0.tar.gz.asc
Source2  : 275C532289DD0F4A.pkey
Summary  : Integration to 'Apache' 'Arrow'
Group    : Development/Tools
License  : Apache-2.0 NCSA
Requires: apache-arrow-data = %{version}-%{release}
Requires: apache-arrow-lib = %{version}-%{release}
Requires: apache-arrow-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : gflags-dev
BuildRequires : glibc-dev
BuildRequires : glog-dev
BuildRequires : gnupg
BuildRequires : google-cloud-cpp-dev
BuildRequires : google-crc32c-dev
BuildRequires : googletest-dev
BuildRequires : libxml2-dev
BuildRequires : llvm-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openssl-dev
BuildRequires : orc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(RapidJSON)
BuildRequires : pkgconfig(grpc++)
BuildRequires : pkgconfig(jemalloc)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libglog)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libutf8proc)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(mimalloc)
BuildRequires : pkgconfig(nlohmann_json)
BuildRequires : pkgconfig(re2)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(thrift)
BuildRequires : pkgconfig(xsimd)
BuildRequires : protobuf-dev
BuildRequires : python3-dev
BuildRequires : snappy-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
development platform for in-memory data. It specifies a standardized
    language-independent columnar memory format for flat and hierarchical data,
    organized for efficient analytic operations on modern hardware. This
    package provides an interface to the 'Arrow C++' library.

%package data
Summary: data components for the apache-arrow package.
Group: Data

%description data
data components for the apache-arrow package.


%package dev
Summary: dev components for the apache-arrow package.
Group: Development
Requires: apache-arrow-lib = %{version}-%{release}
Requires: apache-arrow-data = %{version}-%{release}
Provides: apache-arrow-devel = %{version}-%{release}
Requires: apache-arrow = %{version}-%{release}

%description dev
dev components for the apache-arrow package.


%package doc
Summary: doc components for the apache-arrow package.
Group: Documentation

%description doc
doc components for the apache-arrow package.


%package lib
Summary: lib components for the apache-arrow package.
Group: Libraries
Requires: apache-arrow-data = %{version}-%{release}
Requires: apache-arrow-license = %{version}-%{release}

%description lib
lib components for the apache-arrow package.


%package license
Summary: license components for the apache-arrow package.
Group: Default

%description license
license components for the apache-arrow package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 275C532289DD0F4A' gpg.status
%setup -q -n apache-arrow-17.0.0
cd %{_builddir}/apache-arrow-17.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726787808
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ../cpp --preset "ninja-debug-python-maximal" \
-DARROW_AZURE=OFF \
-DARROW_CUDA=OFF \
-DARROW_DEPENDENCY_SOURCE=SYSTEM \
-DARROW_DEPENDENCY_USE_SHARED=ON \
-DARROW_JEMALLOC=OFF \
-DARROW_MIMALLOC=OFF \
-DARROW_ORC=OFF \
-DARROW_S3=OFF \
-DARROW_SUBSTRAIT=OFF \
-DFETCHCONTENT_FULLY_DISCONNECTED=ON \
-DLZ4_LIB=/usr/lib64/liblz4.so \
-DORC_INCLUDE_DIR=/usr/include  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726787808
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/apache-arrow
cp %{_builddir}/apache-arrow-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/78035d3fd6d040794c41d6343b575b9ab0d88454 || :
cp %{_builddir}/apache-arrow-%{version}/dev/tasks/conda-recipes/arrow-cpp/LLVM_LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/835debc425f3db6a5922d7f1b7af45b6833e92f8 || :
cp %{_builddir}/apache-arrow-%{version}/dev/tasks/linux-packages/apache-arrow-apt-source/debian/copyright %{buildroot}/usr/share/package-licenses/apache-arrow/586da3df733cd5a5baa2445ea28d0238a1ae17eb || :
cp %{_builddir}/apache-arrow-%{version}/dev/tasks/linux-packages/apache-arrow/debian/copyright %{buildroot}/usr/share/package-licenses/apache-arrow/f80c737ae94d813116d7c6098da413c09a7495b6 || :
cp %{_builddir}/apache-arrow-%{version}/go/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/365aeddba4c0add3b3c44ecafd6eb82f30f35a1a || :
cp %{_builddir}/apache-arrow-%{version}/java/dev/license/asf-java.license %{buildroot}/usr/share/package-licenses/apache-arrow/b942b73d483e9ab678103eaebc7e0ddc4646a924 || :
cp %{_builddir}/apache-arrow-%{version}/java/vector/src/main/codegen/includes/license.ftl %{buildroot}/usr/share/package-licenses/apache-arrow/dd239078602e993fcbe894c2f223192b719923d9 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-arrow-cuda/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-arrow-dataset/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-arrow-flight-sql/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-arrow-flight/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-arrow/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-gandiva/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/apache-arrow-%{version}/ruby/red-parquet/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/arrow/gdb/gdb_arrow.py
/usr/share/gdb/auto-load/usr/lib64/libarrow.so.1700.0.0-gdb.py

%files dev
%defattr(-,root,root,-)
/usr/include/arrow/acero/accumulation_queue.h
/usr/include/arrow/acero/aggregate_node.h
/usr/include/arrow/acero/api.h
/usr/include/arrow/acero/asof_join_node.h
/usr/include/arrow/acero/backpressure_handler.h
/usr/include/arrow/acero/benchmark_util.h
/usr/include/arrow/acero/bloom_filter.h
/usr/include/arrow/acero/exec_plan.h
/usr/include/arrow/acero/hash_join.h
/usr/include/arrow/acero/hash_join_dict.h
/usr/include/arrow/acero/hash_join_node.h
/usr/include/arrow/acero/map_node.h
/usr/include/arrow/acero/options.h
/usr/include/arrow/acero/order_by_impl.h
/usr/include/arrow/acero/partition_util.h
/usr/include/arrow/acero/pch.h
/usr/include/arrow/acero/query_context.h
/usr/include/arrow/acero/schema_util.h
/usr/include/arrow/acero/task_util.h
/usr/include/arrow/acero/test_nodes.h
/usr/include/arrow/acero/time_series_util.h
/usr/include/arrow/acero/tpch_node.h
/usr/include/arrow/acero/type_fwd.h
/usr/include/arrow/acero/unmaterialized_table.h
/usr/include/arrow/acero/util.h
/usr/include/arrow/acero/visibility.h
/usr/include/arrow/api.h
/usr/include/arrow/array.h
/usr/include/arrow/array/array_base.h
/usr/include/arrow/array/array_binary.h
/usr/include/arrow/array/array_decimal.h
/usr/include/arrow/array/array_dict.h
/usr/include/arrow/array/array_nested.h
/usr/include/arrow/array/array_primitive.h
/usr/include/arrow/array/array_run_end.h
/usr/include/arrow/array/builder_adaptive.h
/usr/include/arrow/array/builder_base.h
/usr/include/arrow/array/builder_binary.h
/usr/include/arrow/array/builder_decimal.h
/usr/include/arrow/array/builder_dict.h
/usr/include/arrow/array/builder_nested.h
/usr/include/arrow/array/builder_primitive.h
/usr/include/arrow/array/builder_run_end.h
/usr/include/arrow/array/builder_time.h
/usr/include/arrow/array/builder_union.h
/usr/include/arrow/array/concatenate.h
/usr/include/arrow/array/data.h
/usr/include/arrow/array/diff.h
/usr/include/arrow/array/util.h
/usr/include/arrow/array/validate.h
/usr/include/arrow/buffer.h
/usr/include/arrow/buffer_builder.h
/usr/include/arrow/builder.h
/usr/include/arrow/c/abi.h
/usr/include/arrow/c/bridge.h
/usr/include/arrow/c/dlpack.h
/usr/include/arrow/c/dlpack_abi.h
/usr/include/arrow/c/helpers.h
/usr/include/arrow/chunk_resolver.h
/usr/include/arrow/chunked_array.h
/usr/include/arrow/compare.h
/usr/include/arrow/compute/api.h
/usr/include/arrow/compute/api_aggregate.h
/usr/include/arrow/compute/api_scalar.h
/usr/include/arrow/compute/api_vector.h
/usr/include/arrow/compute/cast.h
/usr/include/arrow/compute/exec.h
/usr/include/arrow/compute/expression.h
/usr/include/arrow/compute/function.h
/usr/include/arrow/compute/function_options.h
/usr/include/arrow/compute/kernel.h
/usr/include/arrow/compute/ordering.h
/usr/include/arrow/compute/registry.h
/usr/include/arrow/compute/row/grouper.h
/usr/include/arrow/compute/type_fwd.h
/usr/include/arrow/compute/util.h
/usr/include/arrow/config.h
/usr/include/arrow/csv/api.h
/usr/include/arrow/csv/chunker.h
/usr/include/arrow/csv/column_builder.h
/usr/include/arrow/csv/column_decoder.h
/usr/include/arrow/csv/converter.h
/usr/include/arrow/csv/invalid_row.h
/usr/include/arrow/csv/options.h
/usr/include/arrow/csv/parser.h
/usr/include/arrow/csv/reader.h
/usr/include/arrow/csv/test_common.h
/usr/include/arrow/csv/type_fwd.h
/usr/include/arrow/csv/writer.h
/usr/include/arrow/dataset/api.h
/usr/include/arrow/dataset/dataset.h
/usr/include/arrow/dataset/dataset_writer.h
/usr/include/arrow/dataset/discovery.h
/usr/include/arrow/dataset/file_base.h
/usr/include/arrow/dataset/file_csv.h
/usr/include/arrow/dataset/file_ipc.h
/usr/include/arrow/dataset/file_json.h
/usr/include/arrow/dataset/file_orc.h
/usr/include/arrow/dataset/file_parquet.h
/usr/include/arrow/dataset/parquet_encryption_config.h
/usr/include/arrow/dataset/partition.h
/usr/include/arrow/dataset/pch.h
/usr/include/arrow/dataset/plan.h
/usr/include/arrow/dataset/projector.h
/usr/include/arrow/dataset/scanner.h
/usr/include/arrow/dataset/type_fwd.h
/usr/include/arrow/dataset/visibility.h
/usr/include/arrow/datum.h
/usr/include/arrow/device.h
/usr/include/arrow/extension/fixed_shape_tensor.h
/usr/include/arrow/extension_type.h
/usr/include/arrow/filesystem/api.h
/usr/include/arrow/filesystem/azurefs.h
/usr/include/arrow/filesystem/filesystem.h
/usr/include/arrow/filesystem/filesystem_library.h
/usr/include/arrow/filesystem/gcsfs.h
/usr/include/arrow/filesystem/hdfs.h
/usr/include/arrow/filesystem/localfs.h
/usr/include/arrow/filesystem/mockfs.h
/usr/include/arrow/filesystem/path_util.h
/usr/include/arrow/filesystem/s3_test_util.h
/usr/include/arrow/filesystem/s3fs.h
/usr/include/arrow/filesystem/test_util.h
/usr/include/arrow/filesystem/type_fwd.h
/usr/include/arrow/flight/api.h
/usr/include/arrow/flight/client.h
/usr/include/arrow/flight/client_auth.h
/usr/include/arrow/flight/client_cookie_middleware.h
/usr/include/arrow/flight/client_middleware.h
/usr/include/arrow/flight/client_tracing_middleware.h
/usr/include/arrow/flight/middleware.h
/usr/include/arrow/flight/otel_logging.h
/usr/include/arrow/flight/pch.h
/usr/include/arrow/flight/platform.h
/usr/include/arrow/flight/server.h
/usr/include/arrow/flight/server_auth.h
/usr/include/arrow/flight/server_middleware.h
/usr/include/arrow/flight/server_tracing_middleware.h
/usr/include/arrow/flight/sql/api.h
/usr/include/arrow/flight/sql/client.h
/usr/include/arrow/flight/sql/column_metadata.h
/usr/include/arrow/flight/sql/server.h
/usr/include/arrow/flight/sql/server_session_middleware.h
/usr/include/arrow/flight/sql/server_session_middleware_factory.h
/usr/include/arrow/flight/sql/types.h
/usr/include/arrow/flight/sql/visibility.h
/usr/include/arrow/flight/test_definitions.h
/usr/include/arrow/flight/test_util.h
/usr/include/arrow/flight/transport.h
/usr/include/arrow/flight/transport_server.h
/usr/include/arrow/flight/type_fwd.h
/usr/include/arrow/flight/types.h
/usr/include/arrow/flight/types_async.h
/usr/include/arrow/flight/visibility.h
/usr/include/arrow/integration/json_integration.h
/usr/include/arrow/io/api.h
/usr/include/arrow/io/buffered.h
/usr/include/arrow/io/caching.h
/usr/include/arrow/io/compressed.h
/usr/include/arrow/io/concurrency.h
/usr/include/arrow/io/file.h
/usr/include/arrow/io/hdfs.h
/usr/include/arrow/io/interfaces.h
/usr/include/arrow/io/memory.h
/usr/include/arrow/io/mman.h
/usr/include/arrow/io/slow.h
/usr/include/arrow/io/stdio.h
/usr/include/arrow/io/test_common.h
/usr/include/arrow/io/transform.h
/usr/include/arrow/io/type_fwd.h
/usr/include/arrow/ipc/api.h
/usr/include/arrow/ipc/dictionary.h
/usr/include/arrow/ipc/feather.h
/usr/include/arrow/ipc/json_simple.h
/usr/include/arrow/ipc/message.h
/usr/include/arrow/ipc/options.h
/usr/include/arrow/ipc/reader.h
/usr/include/arrow/ipc/test_common.h
/usr/include/arrow/ipc/type_fwd.h
/usr/include/arrow/ipc/util.h
/usr/include/arrow/ipc/writer.h
/usr/include/arrow/json/api.h
/usr/include/arrow/json/chunked_builder.h
/usr/include/arrow/json/chunker.h
/usr/include/arrow/json/converter.h
/usr/include/arrow/json/object_parser.h
/usr/include/arrow/json/object_writer.h
/usr/include/arrow/json/options.h
/usr/include/arrow/json/parser.h
/usr/include/arrow/json/rapidjson_defs.h
/usr/include/arrow/json/reader.h
/usr/include/arrow/json/test_common.h
/usr/include/arrow/json/type_fwd.h
/usr/include/arrow/memory_pool.h
/usr/include/arrow/memory_pool_test.h
/usr/include/arrow/pch.h
/usr/include/arrow/pretty_print.h
/usr/include/arrow/record_batch.h
/usr/include/arrow/result.h
/usr/include/arrow/scalar.h
/usr/include/arrow/sparse_tensor.h
/usr/include/arrow/status.h
/usr/include/arrow/stl.h
/usr/include/arrow/stl_allocator.h
/usr/include/arrow/stl_iterator.h
/usr/include/arrow/table.h
/usr/include/arrow/table_builder.h
/usr/include/arrow/tensor.h
/usr/include/arrow/tensor/converter.h
/usr/include/arrow/testing/async_test_util.h
/usr/include/arrow/testing/builder.h
/usr/include/arrow/testing/executor_util.h
/usr/include/arrow/testing/extension_type.h
/usr/include/arrow/testing/fixed_width_test_util.h
/usr/include/arrow/testing/future_util.h
/usr/include/arrow/testing/generator.h
/usr/include/arrow/testing/gtest_compat.h
/usr/include/arrow/testing/gtest_util.h
/usr/include/arrow/testing/matchers.h
/usr/include/arrow/testing/pch.h
/usr/include/arrow/testing/random.h
/usr/include/arrow/testing/uniform_real.h
/usr/include/arrow/testing/util.h
/usr/include/arrow/testing/visibility.h
/usr/include/arrow/type.h
/usr/include/arrow/type_fwd.h
/usr/include/arrow/type_traits.h
/usr/include/arrow/util/algorithm.h
/usr/include/arrow/util/align_util.h
/usr/include/arrow/util/aligned_storage.h
/usr/include/arrow/util/async_generator.h
/usr/include/arrow/util/async_generator_fwd.h
/usr/include/arrow/util/async_util.h
/usr/include/arrow/util/base64.h
/usr/include/arrow/util/basic_decimal.h
/usr/include/arrow/util/benchmark_util.h
/usr/include/arrow/util/binary_view_util.h
/usr/include/arrow/util/bit_block_counter.h
/usr/include/arrow/util/bit_run_reader.h
/usr/include/arrow/util/bit_stream_utils.h
/usr/include/arrow/util/bit_util.h
/usr/include/arrow/util/bitmap.h
/usr/include/arrow/util/bitmap_builders.h
/usr/include/arrow/util/bitmap_generate.h
/usr/include/arrow/util/bitmap_ops.h
/usr/include/arrow/util/bitmap_reader.h
/usr/include/arrow/util/bitmap_visit.h
/usr/include/arrow/util/bitmap_writer.h
/usr/include/arrow/util/bitset_stack.h
/usr/include/arrow/util/bpacking.h
/usr/include/arrow/util/bpacking64_default.h
/usr/include/arrow/util/bpacking_avx2.h
/usr/include/arrow/util/bpacking_avx512.h
/usr/include/arrow/util/bpacking_default.h
/usr/include/arrow/util/bpacking_neon.h
/usr/include/arrow/util/byte_size.h
/usr/include/arrow/util/cancel.h
/usr/include/arrow/util/checked_cast.h
/usr/include/arrow/util/compare.h
/usr/include/arrow/util/compression.h
/usr/include/arrow/util/concurrent_map.h
/usr/include/arrow/util/config.h
/usr/include/arrow/util/converter.h
/usr/include/arrow/util/counting_semaphore.h
/usr/include/arrow/util/cpu_info.h
/usr/include/arrow/util/crc32.h
/usr/include/arrow/util/debug.h
/usr/include/arrow/util/decimal.h
/usr/include/arrow/util/delimiting.h
/usr/include/arrow/util/dict_util.h
/usr/include/arrow/util/dispatch.h
/usr/include/arrow/util/double_conversion.h
/usr/include/arrow/util/endian.h
/usr/include/arrow/util/float16.h
/usr/include/arrow/util/formatting.h
/usr/include/arrow/util/functional.h
/usr/include/arrow/util/future.h
/usr/include/arrow/util/hash_util.h
/usr/include/arrow/util/hashing.h
/usr/include/arrow/util/int_util.h
/usr/include/arrow/util/int_util_overflow.h
/usr/include/arrow/util/io_util.h
/usr/include/arrow/util/iterator.h
/usr/include/arrow/util/key_value_metadata.h
/usr/include/arrow/util/launder.h
/usr/include/arrow/util/list_util.h
/usr/include/arrow/util/logger.h
/usr/include/arrow/util/logging.h
/usr/include/arrow/util/macros.h
/usr/include/arrow/util/map.h
/usr/include/arrow/util/math_constants.h
/usr/include/arrow/util/memory.h
/usr/include/arrow/util/mutex.h
/usr/include/arrow/util/parallel.h
/usr/include/arrow/util/pcg_random.h
/usr/include/arrow/util/print.h
/usr/include/arrow/util/queue.h
/usr/include/arrow/util/range.h
/usr/include/arrow/util/ree_util.h
/usr/include/arrow/util/regex.h
/usr/include/arrow/util/rle_encoding.h
/usr/include/arrow/util/rows_to_batches.h
/usr/include/arrow/util/simd.h
/usr/include/arrow/util/small_vector.h
/usr/include/arrow/util/sort.h
/usr/include/arrow/util/spaced.h
/usr/include/arrow/util/span.h
/usr/include/arrow/util/stopwatch.h
/usr/include/arrow/util/string.h
/usr/include/arrow/util/string_builder.h
/usr/include/arrow/util/task_group.h
/usr/include/arrow/util/tdigest.h
/usr/include/arrow/util/test_common.h
/usr/include/arrow/util/thread_pool.h
/usr/include/arrow/util/time.h
/usr/include/arrow/util/tracing.h
/usr/include/arrow/util/trie.h
/usr/include/arrow/util/type_fwd.h
/usr/include/arrow/util/type_traits.h
/usr/include/arrow/util/ubsan.h
/usr/include/arrow/util/union_util.h
/usr/include/arrow/util/unreachable.h
/usr/include/arrow/util/uri.h
/usr/include/arrow/util/utf8.h
/usr/include/arrow/util/value_parsing.h
/usr/include/arrow/util/vector.h
/usr/include/arrow/util/visibility.h
/usr/include/arrow/util/windows_compatibility.h
/usr/include/arrow/util/windows_fixup.h
/usr/include/arrow/vendored/ProducerConsumerQueue.h
/usr/include/arrow/vendored/datetime.h
/usr/include/arrow/vendored/datetime/date.h
/usr/include/arrow/vendored/datetime/ios.h
/usr/include/arrow/vendored/datetime/tz.h
/usr/include/arrow/vendored/datetime/tz_private.h
/usr/include/arrow/vendored/datetime/visibility.h
/usr/include/arrow/vendored/double-conversion/bignum-dtoa.h
/usr/include/arrow/vendored/double-conversion/bignum.h
/usr/include/arrow/vendored/double-conversion/cached-powers.h
/usr/include/arrow/vendored/double-conversion/diy-fp.h
/usr/include/arrow/vendored/double-conversion/double-conversion.h
/usr/include/arrow/vendored/double-conversion/double-to-string.h
/usr/include/arrow/vendored/double-conversion/fast-dtoa.h
/usr/include/arrow/vendored/double-conversion/fixed-dtoa.h
/usr/include/arrow/vendored/double-conversion/ieee.h
/usr/include/arrow/vendored/double-conversion/string-to-double.h
/usr/include/arrow/vendored/double-conversion/strtod.h
/usr/include/arrow/vendored/double-conversion/utils.h
/usr/include/arrow/vendored/pcg/pcg_extras.hpp
/usr/include/arrow/vendored/pcg/pcg_random.hpp
/usr/include/arrow/vendored/pcg/pcg_uint128.hpp
/usr/include/arrow/vendored/portable-snippets/debug-trap.h
/usr/include/arrow/vendored/portable-snippets/safe-math.h
/usr/include/arrow/vendored/strptime.h
/usr/include/arrow/vendored/xxhash.h
/usr/include/arrow/vendored/xxhash/xxhash.h
/usr/include/arrow/visit_array_inline.h
/usr/include/arrow/visit_data_inline.h
/usr/include/arrow/visit_scalar_inline.h
/usr/include/arrow/visit_type_inline.h
/usr/include/arrow/visitor.h
/usr/include/arrow/visitor_generate.h
/usr/include/gandiva/annotator.h
/usr/include/gandiva/arrow.h
/usr/include/gandiva/basic_decimal_scalar.h
/usr/include/gandiva/bitmap_accumulator.h
/usr/include/gandiva/cache.h
/usr/include/gandiva/compiled_expr.h
/usr/include/gandiva/condition.h
/usr/include/gandiva/configuration.h
/usr/include/gandiva/date_utils.h
/usr/include/gandiva/decimal_ir.h
/usr/include/gandiva/decimal_scalar.h
/usr/include/gandiva/decimal_type_util.h
/usr/include/gandiva/decimal_xlarge.h
/usr/include/gandiva/dex.h
/usr/include/gandiva/dex_visitor.h
/usr/include/gandiva/encrypt_utils.h
/usr/include/gandiva/engine.h
/usr/include/gandiva/eval_batch.h
/usr/include/gandiva/execution_context.h
/usr/include/gandiva/exported_funcs.h
/usr/include/gandiva/exported_funcs_registry.h
/usr/include/gandiva/expr_decomposer.h
/usr/include/gandiva/expr_validator.h
/usr/include/gandiva/expression.h
/usr/include/gandiva/expression_cache_key.h
/usr/include/gandiva/expression_registry.h
/usr/include/gandiva/field_descriptor.h
/usr/include/gandiva/filter.h
/usr/include/gandiva/formatting_utils.h
/usr/include/gandiva/func_descriptor.h
/usr/include/gandiva/function_holder.h
/usr/include/gandiva/function_holder_maker_registry.h
/usr/include/gandiva/function_ir_builder.h
/usr/include/gandiva/function_registry.h
/usr/include/gandiva/function_registry_arithmetic.h
/usr/include/gandiva/function_registry_common.h
/usr/include/gandiva/function_registry_datetime.h
/usr/include/gandiva/function_registry_hash.h
/usr/include/gandiva/function_registry_math_ops.h
/usr/include/gandiva/function_registry_string.h
/usr/include/gandiva/function_registry_timestamp_arithmetic.h
/usr/include/gandiva/function_signature.h
/usr/include/gandiva/gandiva_aliases.h
/usr/include/gandiva/gandiva_object_cache.h
/usr/include/gandiva/gdv_function_stubs.h
/usr/include/gandiva/hash_utils.h
/usr/include/gandiva/in_holder.h
/usr/include/gandiva/interval_holder.h
/usr/include/gandiva/literal_holder.h
/usr/include/gandiva/llvm_generator.h
/usr/include/gandiva/llvm_includes.h
/usr/include/gandiva/llvm_types.h
/usr/include/gandiva/local_bitmaps_holder.h
/usr/include/gandiva/lru_cache.h
/usr/include/gandiva/lvalue.h
/usr/include/gandiva/native_function.h
/usr/include/gandiva/node.h
/usr/include/gandiva/node_visitor.h
/usr/include/gandiva/pch.h
/usr/include/gandiva/projector.h
/usr/include/gandiva/random_generator_holder.h
/usr/include/gandiva/regex_functions_holder.h
/usr/include/gandiva/regex_util.h
/usr/include/gandiva/selection_vector.h
/usr/include/gandiva/selection_vector_impl.h
/usr/include/gandiva/simple_arena.h
/usr/include/gandiva/to_date_holder.h
/usr/include/gandiva/tree_expr_builder.h
/usr/include/gandiva/value_validity_pair.h
/usr/include/gandiva/visibility.h
/usr/include/parquet/api/io.h
/usr/include/parquet/api/reader.h
/usr/include/parquet/api/schema.h
/usr/include/parquet/api/writer.h
/usr/include/parquet/arrow/reader.h
/usr/include/parquet/arrow/schema.h
/usr/include/parquet/arrow/test_util.h
/usr/include/parquet/arrow/writer.h
/usr/include/parquet/benchmark_util.h
/usr/include/parquet/bloom_filter.h
/usr/include/parquet/bloom_filter_reader.h
/usr/include/parquet/column_page.h
/usr/include/parquet/column_reader.h
/usr/include/parquet/column_scanner.h
/usr/include/parquet/column_writer.h
/usr/include/parquet/encoding.h
/usr/include/parquet/encryption/crypto_factory.h
/usr/include/parquet/encryption/encryption.h
/usr/include/parquet/encryption/file_key_material_store.h
/usr/include/parquet/encryption/file_key_unwrapper.h
/usr/include/parquet/encryption/file_key_wrapper.h
/usr/include/parquet/encryption/file_system_key_material_store.h
/usr/include/parquet/encryption/key_encryption_key.h
/usr/include/parquet/encryption/key_material.h
/usr/include/parquet/encryption/key_metadata.h
/usr/include/parquet/encryption/key_toolkit.h
/usr/include/parquet/encryption/kms_client.h
/usr/include/parquet/encryption/kms_client_factory.h
/usr/include/parquet/encryption/local_wrap_kms_client.h
/usr/include/parquet/encryption/test_encryption_util.h
/usr/include/parquet/encryption/test_in_memory_kms.h
/usr/include/parquet/encryption/two_level_cache_with_expiration.h
/usr/include/parquet/encryption/type_fwd.h
/usr/include/parquet/exception.h
/usr/include/parquet/file_reader.h
/usr/include/parquet/file_writer.h
/usr/include/parquet/hasher.h
/usr/include/parquet/level_comparison.h
/usr/include/parquet/level_comparison_inc.h
/usr/include/parquet/level_conversion.h
/usr/include/parquet/level_conversion_inc.h
/usr/include/parquet/metadata.h
/usr/include/parquet/page_index.h
/usr/include/parquet/parquet_version.h
/usr/include/parquet/pch.h
/usr/include/parquet/platform.h
/usr/include/parquet/printer.h
/usr/include/parquet/properties.h
/usr/include/parquet/schema.h
/usr/include/parquet/statistics.h
/usr/include/parquet/stream_reader.h
/usr/include/parquet/stream_writer.h
/usr/include/parquet/test_util.h
/usr/include/parquet/type_fwd.h
/usr/include/parquet/types.h
/usr/include/parquet/windows_compatibility.h
/usr/include/parquet/windows_fixup.h
/usr/include/parquet/xxhasher.h
/usr/lib64/cmake/Arrow/ArrowConfig.cmake
/usr/lib64/cmake/Arrow/ArrowConfigVersion.cmake
/usr/lib64/cmake/Arrow/ArrowOptions.cmake
/usr/lib64/cmake/Arrow/ArrowTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Arrow/ArrowTargets.cmake
/usr/lib64/cmake/Arrow/FindBrotliAlt.cmake
/usr/lib64/cmake/Arrow/FindOpenSSLAlt.cmake
/usr/lib64/cmake/Arrow/FindSnappyAlt.cmake
/usr/lib64/cmake/Arrow/Findlz4Alt.cmake
/usr/lib64/cmake/Arrow/Findre2Alt.cmake
/usr/lib64/cmake/Arrow/Findutf8proc.cmake
/usr/lib64/cmake/Arrow/FindzstdAlt.cmake
/usr/lib64/cmake/Arrow/arrow-config.cmake
/usr/lib64/cmake/ArrowAcero/ArrowAceroConfig.cmake
/usr/lib64/cmake/ArrowAcero/ArrowAceroConfigVersion.cmake
/usr/lib64/cmake/ArrowAcero/ArrowAceroTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowAcero/ArrowAceroTargets.cmake
/usr/lib64/cmake/ArrowDataset/ArrowDatasetConfig.cmake
/usr/lib64/cmake/ArrowDataset/ArrowDatasetConfigVersion.cmake
/usr/lib64/cmake/ArrowDataset/ArrowDatasetTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowDataset/ArrowDatasetTargets.cmake
/usr/lib64/cmake/ArrowFlight/ArrowFlightConfig.cmake
/usr/lib64/cmake/ArrowFlight/ArrowFlightConfigVersion.cmake
/usr/lib64/cmake/ArrowFlight/ArrowFlightTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowFlight/ArrowFlightTargets.cmake
/usr/lib64/cmake/ArrowFlight/FindProtobufAlt.cmake
/usr/lib64/cmake/ArrowFlight/FindgRPCAlt.cmake
/usr/lib64/cmake/ArrowFlightSql/ArrowFlightSqlConfig.cmake
/usr/lib64/cmake/ArrowFlightSql/ArrowFlightSqlConfigVersion.cmake
/usr/lib64/cmake/ArrowFlightSql/ArrowFlightSqlTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowFlightSql/ArrowFlightSqlTargets.cmake
/usr/lib64/cmake/ArrowFlightTesting/ArrowFlightTestingConfig.cmake
/usr/lib64/cmake/ArrowFlightTesting/ArrowFlightTestingConfigVersion.cmake
/usr/lib64/cmake/ArrowFlightTesting/ArrowFlightTestingTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowFlightTesting/ArrowFlightTestingTargets.cmake
/usr/lib64/cmake/ArrowTesting/ArrowTestingConfig.cmake
/usr/lib64/cmake/ArrowTesting/ArrowTestingConfigVersion.cmake
/usr/lib64/cmake/ArrowTesting/ArrowTestingTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ArrowTesting/ArrowTestingTargets.cmake
/usr/lib64/cmake/ArrowTesting/FindGTestAlt.cmake
/usr/lib64/cmake/Gandiva/FindLLVMAlt.cmake
/usr/lib64/cmake/Gandiva/FindzstdAlt.cmake
/usr/lib64/cmake/Gandiva/GandivaAddBitcode.cmake
/usr/lib64/cmake/Gandiva/GandivaConfig.cmake
/usr/lib64/cmake/Gandiva/GandivaConfigVersion.cmake
/usr/lib64/cmake/Gandiva/GandivaTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Gandiva/GandivaTargets.cmake
/usr/lib64/cmake/Parquet/FindThriftAlt.cmake
/usr/lib64/cmake/Parquet/ParquetConfig.cmake
/usr/lib64/cmake/Parquet/ParquetConfigVersion.cmake
/usr/lib64/cmake/Parquet/ParquetTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Parquet/ParquetTargets.cmake
/usr/lib64/libarrow.so
/usr/lib64/libarrow_acero.so
/usr/lib64/libarrow_dataset.so
/usr/lib64/libarrow_flight.so
/usr/lib64/libarrow_flight_sql.so
/usr/lib64/libarrow_flight_testing.so
/usr/lib64/libarrow_testing.so
/usr/lib64/libgandiva.so
/usr/lib64/libparquet.so
/usr/lib64/pkgconfig/arrow-acero.pc
/usr/lib64/pkgconfig/arrow-compute.pc
/usr/lib64/pkgconfig/arrow-csv.pc
/usr/lib64/pkgconfig/arrow-dataset.pc
/usr/lib64/pkgconfig/arrow-filesystem.pc
/usr/lib64/pkgconfig/arrow-flight-sql.pc
/usr/lib64/pkgconfig/arrow-flight-testing.pc
/usr/lib64/pkgconfig/arrow-flight.pc
/usr/lib64/pkgconfig/arrow-json.pc
/usr/lib64/pkgconfig/arrow-testing.pc
/usr/lib64/pkgconfig/arrow.pc
/usr/lib64/pkgconfig/gandiva.pc
/usr/lib64/pkgconfig/parquet.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/arrow/LICENSE.txt
/usr/share/doc/arrow/NOTICE.txt
/usr/share/doc/arrow/README.md

%files lib
%defattr(-,root,root,-)
/usr/lib64/libarrow.so.1700
/usr/lib64/libarrow.so.1700.0.0
/usr/lib64/libarrow_acero.so.1700
/usr/lib64/libarrow_acero.so.1700.0.0
/usr/lib64/libarrow_dataset.so.1700
/usr/lib64/libarrow_dataset.so.1700.0.0
/usr/lib64/libarrow_flight.so.1700
/usr/lib64/libarrow_flight.so.1700.0.0
/usr/lib64/libarrow_flight_sql.so.1700
/usr/lib64/libarrow_flight_sql.so.1700.0.0
/usr/lib64/libarrow_flight_testing.so.1700
/usr/lib64/libarrow_flight_testing.so.1700.0.0
/usr/lib64/libarrow_testing.so.1700
/usr/lib64/libarrow_testing.so.1700.0.0
/usr/lib64/libgandiva.so.1700
/usr/lib64/libgandiva.so.1700.0.0
/usr/lib64/libparquet.so.1700
/usr/lib64/libparquet.so.1700.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/apache-arrow/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/apache-arrow/365aeddba4c0add3b3c44ecafd6eb82f30f35a1a
/usr/share/package-licenses/apache-arrow/586da3df733cd5a5baa2445ea28d0238a1ae17eb
/usr/share/package-licenses/apache-arrow/78035d3fd6d040794c41d6343b575b9ab0d88454
/usr/share/package-licenses/apache-arrow/835debc425f3db6a5922d7f1b7af45b6833e92f8
/usr/share/package-licenses/apache-arrow/b942b73d483e9ab678103eaebc7e0ddc4646a924
/usr/share/package-licenses/apache-arrow/dd239078602e993fcbe894c2f223192b719923d9
/usr/share/package-licenses/apache-arrow/f80c737ae94d813116d7c6098da413c09a7495b6
